### ISSUE TITLE
Key tower/fully_connected/weights not found in checkpoint

### ISSUE THREAD

**Issue by hhhhnwl** [miha-skalic/youtube8mchallange#2]
I have traind a NetVLAD model,when I train NetVLAD_ema  got this error:

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Key tower/fully_connected/weights not found in checkpoint
INFO:tensorflow:train_2018_9_13/NetVLAD_ema/model.ckpt-0 is not in all_model_checkpoint_paths. Manually adding it.
INFO:tensorflow:Recording summary at step 0.
Traceback (most recent call last):
  File "train.py", line 770, in <module>
    app.run()
  File "/data1/local/python2.7.15/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 761, in main
    FLAGS.export_model_steps).run(start_new_model=FLAGS.start_new_model)
  File "train.py", line 494, in run
    src_tensor = ckpt_reader.get_tensor(xtensor.name.split(":")[0])
  File "/data1/local/python2.7.15/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 192, in get_tensor
    status)
  File "/data1/local/python2.7.15/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key tower/fully_connected/weights not found in checkpoint

**Comment by miha-skalic** [comment]
hi,

with just the error message it is hard to guess what went wrong. Could you provide both calls that you do (to train initial model and EMA model)? My guess is that there is some difference between model arhitecture of EMA and non EMA models.

**Comment by hhhhnwl** [comment]
Thanks  for your answer.

 train initial model:
 python train.py \
     --train_data_pattern="/data/yt8m/train*.tfrecord" \
     --model=NetVLADModelLF \
     --train_dir="train_2018_9_13//NetVLAD" \
     --frame_features=True --feature_names="rgb,audio" \
     --feature_sizes="1024,128" \
     --batch_size=160 --base_learning_rate=0.0002 \
     --netvlad_cluster_size=256 \
     --netvlad_hidden_size=1024 \
     --moe_l2=1e-6 --iterations=300 \
     --learning_rate_decay=0.8 \
     --netvlad_relu=False \
     --gating=True \
     --moe_prob_gating=True \
     --lightvlad=False \
     --num_gpu 1 \
     --max_steps=154962 \

train EMA model:
python train.py \
     --train_data_pattern="/data/yt8m/train*.tfrecord" \
     --model=NetVLADModelLF \
     --train_dir="train_2018_9_13/NetVLAD_ema" \
     --video_level_classifier_model="LogisticModel" \
     --frame_features \
     --feature_names="rgb, audio" \
     --feature_sizes="1024, 128" \
     --batch_size=160 \
     --base_learning_rate=0.00008 \
     --lstm_cells=1024 \
     --num_epochs=2 \
     --num_gpu 1 \
     --num_readers 8 \
     --loss_lambda 0.5 \
    --ema_halflife 2000 \
     --ema_source "train_2018_9_13/NetVLAD/model.ckpt-154962"

**Comment by hhhhnwl** [comment]
oh, I changed the default value of "netvlad_cluster_size" to 256 in devel_models.py

**Comment by miha-skalic** [comment]
netvlad_cluster_size could be 1 thing, there are also other problematic components such as `--video_level_classifier_model="LogisticModel" ` set in second call those have to match in both cases. 
You also have redundant flags: `lstm_cells` will be ignored with NetVLADModelLF model.

**Comment by hhhhnwl** [comment]
I change the second call like this and it words:
python train.py \
     --train_data_pattern="/data/yt8m/train*.tfrecord" \
     --model=NetVLADModelLF \
     --train_dir="train_2018_9_13//NetVLAD_ema" \
     --frame_features=True --feature_names="rgb,audio" \
     --feature_sizes="1024,128" \
     --batch_size=160 --base_learning_rate=0.00008 \                                                                        
     --netvlad_cluster_size=256 \
     --netvlad_hidden_size=1024 \
     --moe_l2=1e-6 --iterations=300 \
     --learning_rate_decay=0.8 \
     --netvlad_relu=False \
     --gating=True \
     --moe_prob_gating=True \
     --lightvlad=False \
     --num_gpu 1 \
     --num_epochs=2 \
     --loss_lambda 0.5 \
     --ema_source "train_2018_9_13/NetVLAD/model.ckpt-154962"

**Comment by miha-skalic** [comment]
I'm glad to hear that  it worked. One thing to note is that we did not see much improvement on netVLAD when using ema. The biggest gains were on LSTM models.

**Comment by hhhhnwl** [comment]
Wow, could you please give me an example of the both 1st and 2ed call to LSTM models?
