### ISSUE TITLE
pre-trained model availability

### ISSUE THREAD

**Issue by estathop** [miha-skalic/youtube8mchallange#4]
Congrats for winning the competition. 
By any chance, is it possible for you to provide your pre-trained model with a little bit of documentation on how to use it ?

**Comment by miha-skalic** [comment]
Sure thing!

I will upload them later today.

Best, 
Miha

**Comment by miha-skalic** [comment]
The pre-trained model is now available. see README for more info.

**Comment by estathop** [comment]
Thanks, closed
